CREATE TABLE employee(
eno char(4 BYTE)PRIMARY KEY,
ENAME VARCHAR2(3O BYTE)UNIQUE,
job VARCHAR2(30 BYTE) UNIQUE,
manager char(4 BYTE),
JDATE TIMESTAMP UNIQUE,
GENDER CHAR (1 BYTE) CHECK (GENDER IN ('M','F')),
SALARY NUMBER(8,2) CHECK (SALARY>0),
COMISSION NUMBER(8,2) DEFAULT 0,
DEPTNO NUMBER (*,0)
);
CREATE TABLE DEPARTMENT(
DNO NUMBER (*,0),
DNAME VARCHAR2(30 BYTE) UNIQUE,
DLOCATION VARCHAR2(30 BYTE)
);
INSERT INTO Department (DNO, DNAME,DLOCATION)
VALUES INTO (1,'SALES','TORONTO');
INSERT INTO Department (DNO, DNAME,DLOCATION)
VALUES INTO (2,'ACCOUNTAING','TORONTO');
INSERT INTO Department (DNO, DNAME,DLOCATION)
VALUES INTO (3,'LEGAL','TORONTO');
INSERT INTO Department (DNO, DNAME,DLOCATION)
VALUES INTO (4,'MARKETING','TORONTO');
INSERT INTO Department (DNO, DNAME,DLOCATION)
VALUES INTO (5,'PERSONAL RELATIONS','TORONTO');

INSERT INTO employee (ENO, ENAME, JOB, MANAGER, JDATE, GENDER, SALARY, COMMISSION, DNO)
VALUES INTO (001, 'John', 'Manager', NULL, TIMESTAMP '2023-06-22 10:00:00', 'M', 50000, 0, 1);
INSERT INTO employee (ENO, ENAME, JOB, MANAGER, JDATE, GENDER, SALARY, COMMISSION, DNO)
VALUES INTO (002, 'Josh', 'lawyer', NULL, TIMESTAMP '2023-06-22 10:00:00', 'M', 50001, 0, 2);
INSERT INTO employee (ENO, ENAME, JOB, MANAGER, JDATE, GENDER, SALARY, COMMISSION, DNO)
VALUES INTO (003, 'Jake', 'human relations', NULL, TIMESTAMP '2023-06-22 10:00:00', 'M', 50002, 0, 3);
INSERT INTO employee (ENO, ENAME, JOB, MANAGER, JDATE, GENDER, SALARY, COMMISSION, DNO)
VALUES INTO (004, 'John', 'Sales Agent', NULL, TIMESTAMP '2023-06-22 10:00:00', 'M', 40000, 0, 4);
INSERT INTO employee (ENO, ENAME, JOB, MANAGER, JDATE, GENDER, SALARY, COMMISSION, DNO)
VALUES INTO (005, 'Charlotte', 'Social Media Campaigner', NULL, TIMESTAMP '2023-06-22 10:00:00', 'F', 880000, 0, 5);